name: Publish game to GitHub Pages

on:
  push:
    branches:
      - ll2-scrambler

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Modify the list below to change what projects are published.
      # To publish only loonyland2:
      #   ./tools/build/distribute-web.sh loonyland2
      # To publish everything:
      #   ./tools/build/distribute-web.sh
      - run: |
          ./tools/build/distribute-web.sh loonyland2

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/webroot
          force_orphan: true
